// Rewriting benchmark: [mode, input, expected output]. Expected outputs are
// grammatical, meaning-preserving edits; "unchanged" cases guard against
// corrupting text the editor has no reason to touch.
export const CASES = [
  // --- core wordy phrases (all modes)
  ["clear", "We met in order to plan the launch.", "We met to plan the launch."],
  ["clear", "In order to win, we trained daily.", "To win, we trained daily."],
  ["clear", "The game was cancelled due to the fact that it rained.", "The game was cancelled because it rained."],
  ["clear", "Despite the fact that it was late, she stayed.", "Although it was late, she stayed."],
  ["clear", "At this point in time we have no data.", "Now we have no data."],
  ["clear", "Call me in the event that the server fails.", "Call me if the server fails."],
  ["clear", "The robot has the ability to climb stairs.", "The robot can climb stairs."],
  ["clear", "The old model had the ability to fly.", "The old model could fly."],
  ["clear", "We make use of open data.", "We use open data."],
  ["clear", "She made use of every minute.", "She used every minute."],
  ["clear", "They are making use of the lab.", "They are using the lab."],
  ["clear", "He makes use of templates.", "He uses templates."],
  ["clear", "I have a question with regard to the budget.", "I have a question about the budget."],
  ["clear", "A large number of people attended.", "Many people attended."],
  ["clear", "The majority of voters agreed.", "Most voters agreed."],
  ["clear", "We will ship it in the near future.", "We will ship it soon."],
  ["clear", "We back up on a daily basis.", "We back up daily."],
  ["clear", "The team made a decision to wait.", "The team decided to wait."],
  ["clear", "They will make a decision tomorrow.", "They will decide tomorrow."],
  ["clear", "We came to the conclusion that it works.", "We concluded that it works."],
  ["clear", "Please give consideration to my request.", "Please consider my request."],
  ["clear", "We are in the process of reviewing the files.", "We are reviewing the files."],
  ["clear", "The board conducted an investigation into the loss.", "The board investigated the loss."],
  ["clear", "The the report is ready.", "The report is ready."],
  ["clear", "Send it to to the editor.", "Send it to the editor."],
  // --- concise mode
  ["concise", "It is important to note that the tests passed.", "Note that the tests passed."],
  ["concise", "Each and every item was checked.", "Each item was checked."],
  ["concise", "The final outcome surprised us.", "The outcome surprised us."],
  ["concise", "Needless to say, the plan failed.", "The plan failed."],
  ["concise", "It rained. Needless to say, the picnic was cancelled.", "It rained. The picnic was cancelled."],
  ["concise", "Basically, the idea is simple.", "The idea is simple."],
  ["concise", "We need to decide whether or not to go.", "We need to decide whether to go."],
  ["concise", "The end results were positive.", "The results were positive."],
  ["concise", "They collaborated together on the paper.", "They collaborated on the paper."],
  ["concise", "Please do not revert back the change.", "Please do not revert the change."],
  ["concise", "The problem still remains unsolved.", "The problem remains unsolved."],
  ["concise", "This is a very unique design.", "This is a unique design."],
  ["concise", "In spite of the rain, we played.", "Despite the rain, we played."],
  ["concise", "The fire completely eliminated the risk.", "The fire eliminated the risk."],
  // --- plain mode: inflection-aware and article-safe
  ["plain", "We utilize cloud storage.", "We use cloud storage."],
  ["plain", "The team utilized three servers.", "The team used three servers."],
  ["plain", "She is utilizing the new tool.", "She is using the new tool."],
  ["plain", "The contract terminated in May.", "The contract ended in May."],
  ["plain", "They obtained permits last year.", "They got permits last year."],
  ["plain", "The results demonstrate a clear trend.", "The results show a clear trend."],
  ["plain", "There is an additional fee.", "There is an extra fee."],
  ["plain", "The additional cost was small.", "The extra cost was small."],
  ["plain", "We need additional information.", "We need extra information."],
  ["plain", "We have sufficient funds.", "We have enough funds."],
  ["plain", "We hired a sufficient number of staff.", "We hired enough staff."],
  ["plain", "It was late. Nevertheless, we continued.", "It was late. Still, we continued."],
  ["plain", "Numerous studies agree.", "Many studies agree."],
  ["plain", "Wash your hands prior to eating.", "Wash your hands before eating."],
  ["plain", "The trip costs approximately $40.", "The trip costs about $40."],
  ["plain", "We will purchase a new laptop.", "We will buy a new laptop."],
  ["plain", "They purchased the house in 2019.", "They purchased the house in 2019.".replace("purchased the", "bought the")],
  ["plain", "The purchase was approved.", "The purchase was approved."],
  ["plain", "Employees are required to sign in.", "Employees must sign in."],
  ["plain", "We will endeavor to respond quickly.", "We will try to respond quickly."],
  ["plain", "Thank you for your assistance.", "Thank you for your help."],
  ["plain", "Regarding the budget, we agree.", "About the budget, we agree."],
  ["plain", "Please ascertain the cause.", "Please find out the cause."],
  // --- must remain unchanged (no reason to edit)
  ["clear", "The U.S.A. and the U.K. signed it.", "The U.S.A. and the U.K. signed it."],
  ["clear", "We built it with Node.JS and Vue.", "We built it with Node.JS and Vue."],
  ["clear", "See file README.MD for details.", "See file README.MD for details."],
  ["clear", "Steps:\n    1. Open the app.\n    2. Tap Check.", "Steps:\n    1. Open the app.\n    2. Tap Check."],
  ["clear", "Name:    Value\nAlpha:   1", "Name:    Value\nAlpha:   1"],
  ["clear", "He said \"we did it in order to win\" and left.", "He said \"we did it in order to win\" and left."],
  ["plain", "Visit https://example.com/utilize-in-order-to for more.", "Visit https://example.com/utilize-in-order-to for more."],
  ["plain", "Run `utilize --in-order-to` now.", "Run `utilize --in-order-to` now."],
  ["clear", "I had had enough.", "I had had enough."],
  ["clear", "She said that that was fine.", "She said that that was fine."],
  ["plain", "The remainder is 3 when dividing 7 by 4.", "The remainder is 3 when dividing 7 by 4."],
  ["plain", "The drug is indicated for pain.", "The drug is indicated for pain."],
  ["clear", "Hello , world ! Is it ok ?", "Hello , world ! Is it ok ?"],
  ["plain", "A noble endeavor deserves support.", "A noble endeavor deserves support."],
  ["clear", "Wait... what?\n\n\nNew section.", "Wait... what?\n\n\nNew section."],
];
